---
# tasks file for database
- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server 

- name: Start service, if not started
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
    
- name: Install pymysql
  ansible.builtin.apt:
    name: python3-pymysql

- name: Create a new database 
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create database user 
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  #create user 'hello'@'localhost' identified by '12345';
  #grant all privileges on *.* to 'bob'@'localhost';