- name: Install apache httpd (state=present is optional)
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true